[package]
name = "rust-playground"
version = "0.1.0"
authors = ["zhixiangyao <blueskyzx@icloud.com>"]
edition = "2021"
github = "https://github.com/zhixiangyao/rust-playground"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
